#Book Resevation
bTitle = input("Enter the book title: ")
bAuthor = input("Enter the author: ")
bYear = int(input("Enter the year of publication: "))
bGenre = input("Enter the genre: ")
bLib = input("Enter the library: ")
mID = input("Enter your member ID: ")
bReturn = input("Enter the return date: ")

print ("You have successfully reserved the book","'"+bTitle+"'", "by", bAuthor, end=".", )
print ("\nYear of Publication:", bYear)
print ("Genre:", bGenre)
print ("Library:", bLib)
print ("Member ID:", mID)
print ("Return Date:", bReturn)

#Email Display Details
#variable
recipient = input("Enter the recipient: ")
msg = input("Enter the message: ")
name = input("Enter the name: ")
sub = input("Enter the subject: ")
ver = float(input("Enter the version: "))
disc = float(input("Enter the discount: "))
status = input("Enter the status: ")
code = input("Enter the code: ")
loc = input("Enter the location: ")
age = int(input("Enter the age: "))
cName = input("Enter the company name: ")
cWeb = input("Enter the website: ")
cPhone = input("Enter the phone: ")
jTitle = input("Enter the job title: ")
jDept = input("Enter the department: ")

#format
disc2 = format(disc, '.2f')

print ("Dear", recipient+",", "I hope this email finds you well.")
print (msg)
print ("Subject:", sub)
print ("Sender:",name)
print ("Version:",ver)
print ("Discount:", disc2+"%")
print ("Status:", status)
print ("Code:",code)
print ("Location:", loc)
print ("Age:", age)
print ("Company:",cName)
print ("Website:", cWeb)
print ("Phone:",cPhone)
print ("Job Title:",jTitle)
print ("Department:",jDept)
